spring.application.name=PgManagment
application.monthly.Rent=2300
server.port=8080

logging.level.root=INFO

spring.datasource.url=jdbc:mysql://localhost:3306/PgManagement?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Shubham14@28#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.producer.bootstrap-servers=172.30.194.117:9093
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shubhamjagdalerxl@gmail.com
spring.mail.password=vaop whct oird vzsy
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=true